# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
    # You can also specify other tool versions:
    # nodejs: "23"
    # rust: "1.82"
    # golang: "1.23"
  apt_packages:
  - build-essential
  - clang
  - cmake
  - cmake-curses-gui
  - git
  - curl
  - xterm
  - libboost-dev
  - libboost-system-dev
  - libboost-timer-dev
  - libboost-mpi-dev
  - libboost-random-dev
  - libomp-dev
  - libeigen3-dev
  - libnetcdf-c++4-dev
  - gfortran
  - libtbb-dev
  - coinor-libcoinutils-dev
  - libbz2-dev
  - liblapack-dev
  - libopenblas-dev
  - zlib1g-dev

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - dev
    - docs
